package com.example.data.remote

import android.content.Context
import android.content.SharedPreferences

class SupabaseConfig(context: Context) {
    private val prefs: SharedPreferences =
        context.getSharedPreferences("supabase_prefs", Context.MODE_PRIVATE)

    var supabaseUrl: String
        get() = prefs.getString("supabase_url", "") ?: ""
        set(value) = prefs.edit().putString("supabase_url", value.trim().removeSuffix("/")).apply()

    var anonKey: String
        get() = prefs.getString("supabase_anon_key", "") ?: ""
        set(value) = prefs.edit().putString("supabase_anon_key", value.trim()).apply()

    var autoSyncEnabled: Boolean
        get() = prefs.getBoolean("auto_sync_enabled", true)
        set(value) = prefs.edit().putBoolean("auto_sync_enabled", value).apply()

    var lastSyncTime: Long
        get() = prefs.getLong("last_sync_time", 0L)
        set(value) = prefs.edit().putLong("last_sync_time", value).apply()

    fun isConfigured(): Boolean {
        return supabaseUrl.isNotBlank() && anonKey.isNotBlank() && supabaseUrl.startsWith("http")
    }

    companion object {
        const val SETUP_SQL = """-- Run this in your Supabase SQL Editor:
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text unique not null
);

create table if not exists brands (
  id bigint generated by default as identity primary key,
  name text unique not null
);

create table if not exists items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  brand text,
  rate numeric not null,
  mm int,
  transmission text,
  specifications text,
  notes text,
  updated_at timestamp default now()
);

create table if not exists invoices (
  id bigint generated by default as identity primary key,
  invoice_number text unique not null,
  customer_name text not null,
  customer_phone text,
  customer_address text,
  date_millis bigint,
  subtotal numeric,
  item_discounts_total numeric,
  overall_discount numeric,
  grand_total numeric,
  status text,
  notes text
);

create table if not exists invoice_items (
  id bigint generated by default as identity primary key,
  invoice_number text not null,
  name text not null,
  category text,
  brand text,
  mm int,
  transmission text,
  original_rate numeric,
  discount_per_unit numeric,
  final_rate numeric,
  quantity int,
  line_total numeric
);
"""
    }
}
